---
# Workflow名
name: module4_task0
# イベントトリガー
# Git Push、Pullした時にこのワークフローを実行する
on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened, edited, ready_for_review, synchronize]

jobs:
  # job名(任意の名前で良い)
  module4_task0:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    # jobのステップ
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd module4_task0/
          chmod u+x setup.sh
          sudo ./setup.sh

      - name: Lint
        run: |
          cd module4_task0/
          make lint

      - name: Build
        run: |
          cd module4_task0/
          make build

      - name: Post
        run: |
          cd module4_task0/
          make POST_TITLE="Test" POST_NAME="name" post

      - name: Run unit tests
        run: |
          cd module4_task0/
          make unit-tests

      - name: Run integration tests
        run: |
          cd module4_task0/
          make integration-tests

      - name: Run validation
        run: |
          cd module4_task0/
          make validate

      - name: Package
        run: |
          cd module4_task0/
          make package

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TOKEN: ${{ secrets.TOKEN }}
        uses: softprops/action-gh-release@v1 # GitHubリリースを作成
        with:
          tag_name: 1.0.1
          files: |
            module4_task0/awesome-website.zip
            module4_task0/DEPLOY.md

      - name: Archive
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: module4_task0/awesome-website.zip

      - name: deploy
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './module4_task0/dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: '🎉 Published on'
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      - name: Clean
        run: |
          cd module4_task0/
          make clean
